CREATE TABLE USER1 AS (SELECT * FROM SYZHAO.PUBLIC_USERS);

DROP TABLE USER1;

INSERT INTO USER1(USER_ID, FIRST_NAME, LAST_NAME)
VALUES(9999, 'Suri', 'Karan');

INSERT INTO USER1(USER_ID, FIRST_NAME, LAST_NAME)
VALUES(9998, 'Yuwei', 'Karan');

SELECT USER_ID, FIRST_NAME, LAST_NAME
FROM USER1
WHERE
USER_ID = ANY
(	SELECT DISTINCT U1.user_id
	FROM USER1 U1
	MINUS
	SELECT DISTINCT F1.user1_id
	FROM SYZHAO.PUBLIC_FRIENDS F1
	MINUS
	SELECT DISTINCT F2.user2_id
	FROM SYZHAO.PUBLIC_FRIENDS F2
);

