SELECT DISTINCT T.TAG_PHOTO_ID, A.ALBUM_ID, A.ALBUM_NAME, P.PHOTO_CAPTION, P.PHOTO_LINK
FROM SYZHAO.PUBLIC_TAGS T, SYZHAO.PUBLIC_PHOTOS P, SYZHAO.PUBLIC_ALBUMS A
WHERE
P.PHOTO_ID = T.TAG_PHOTO_ID AND P.ALBUM_ID = A.ALBUM_ID 
AND T.TAG_PHOTO_ID = ANY(
	SELECT DISTINCT TAG_PHOTO_ID
	FROM(
	SELECT DISTINCT T.TAG_PHOTO_ID, COUNT(T.TAG_PHOTO_ID) AS TAGNUM
	FROM SYZHAO.PUBLIC_TAGS T
	GROUP BY T.TAG_PHOTO_ID
	ORDER BY TAGNUM DESC, T.TAG_PHOTO_ID ASC
	)
	WHERE ROWNUM <= 5)
ORDER BY T.TAG_PHOTO_ID ASC


	
SELECT DISTINCT T.TAG_PHOTO_ID, T.TAG_SUBJECT_ID, U.FIRST_NAME, U.LAST_NAME
FROM SYZHAO.PUBLIC_TAGS T, SYZHAO.PUBLIC_USERS U
WHERE
U.USER_ID = T.TAG_SUBJECT_ID AND T.TAG_PHOTO_ID = ANY(
	SELECT DISTINCT TAG_PHOTO_ID
	FROM(
	SELECT DISTINCT T.TAG_PHOTO_ID, COUNT(T.TAG_PHOTO_ID) AS TAGNUM
	FROM SYZHAO.PUBLIC_TAGS T
	GROUP BY T.TAG_PHOTO_ID
	ORDER BY TAGNUM DESC, T.TAG_PHOTO_ID ASC
	)
	WHERE ROWNUM <= 5)
ORDER BY T.TAG_PHOTO_ID ASC;
