
SELECT 
U1.USER_ID, U1.FIRST_NAME, U1.LAST_NAME, 
U2.USER_ID, U2.FIRST_NAME, U2.LAST_NAME
FROM USER1 U1, USER1 U2,
(	
	SELECT ID1, ID2
	FROM
	(
		SELECT T1.TAG_SUBJECT_ID AS ID1, T2.TAG_SUBJECT_ID AS ID2
		FROM TAG1 T1, TAG1 T2
		WHERE
		T1.TAG_SUBJECT_ID < T2.TAG_SUBJECT_ID
		AND T1.TAG_PHOTO_ID = T2.TAG_PHOTO_ID
		MINUS
		SELECT F.USER1_ID, F.USER2_ID
		FROM SYZHAO.PUBLIC_FRIENDS F
	)
	GROUP BY ID1, ID2
	ORDER BY ID1 ASC, ID2 ASC
)A
WHERE A.ID1 = U1.USER_ID AND A.ID2 = U2.USER_ID AND U1.GENDER = U2.GENDER 
AND ABS(U1.YEAR_OF_BIRTH - U2.YEAR_OF_BIRTH) <= 1 AND ROWNUM <= 2;










CREATE TABLE USER1 AS (SELECT * FROM SYZHAO.PUBLIC_USERS);
CREATE TABLE TAG1 AS (SELECT * FROM SYZHAO.PUBLIC_TAGS);
CREATE TABLE FRIEND1 AS (SELECT * FROM SYZHAO.PUBLIC_FRIENDS);

DROP TABLE USER1;
DROP TABLE TAG1;

INSERT INTO USER1(USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER)
VALUES(9999, 'Karan', 'Suri', 1993, 1, 5, 'male');

INSERT INTO USER1(USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER)
VALUES(9998, 'Yuri', 'Suri', 2018, 1, 5, 'female');

INSERT INTO USER1(USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER)
VALUES(9997, 'Yuwei', 'Suri', 1994, 11, 27, 'female');

INSERT INTO USER1(USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER)
VALUES(9996, 'Chi', 'Zhang', 1994, 11, 27, 'female');



INSERT INTO TAG1(TAG_PHOTO_ID, TAG_SUBJECT_ID)
VALUES(10, 9997);

INSERT INTO TAG1(TAG_PHOTO_ID, TAG_SUBJECT_ID)
VALUES(10, 9998);

INSERT INTO TAG1(TAG_PHOTO_ID, TAG_SUBJECT_ID)
VALUES(9, 9997);

INSERT INTO TAG1(TAG_PHOTO_ID, TAG_SUBJECT_ID)
VALUES(9, 9998);

INSERT INTO TAG1(TAG_PHOTO_ID, TAG_SUBJECT_ID)
VALUES(8, 9997);

INSERT INTO TAG1(TAG_PHOTO_ID, TAG_SUBJECT_ID)
VALUES(8, 9998);


INSERT INTO TAG1(TAG_PHOTO_ID, TAG_SUBJECT_ID)
VALUES(10, 206);

INSERT INTO TAG1(TAG_PHOTO_ID, TAG_SUBJECT_ID)
VALUES(10, 1680);

INSERT INTO TAG1(TAG_PHOTO_ID, TAG_SUBJECT_ID)
VALUES(9, 206);

INSERT INTO TAG1(TAG_PHOTO_ID, TAG_SUBJECT_ID)
VALUES(9, 1680);




