

SELECT DISTINCT
U1.USER_ID, U1.FIRST_NAME, U1.LAST_NAME,
U2.USER_ID, U2.FIRST_NAME, U2.LAST_NAME,
A.CommonFri
FROM SYZHAO.PUBLIC_USERS U1, SYZHAO.PUBLIC_USERS U2,
(
	SELECT
	N.UID1, N.UID2, COUNT(*) AS CommonFri
	FROM
	(
		SELECT F.USER1_ID AS ID1, F.USER2_ID AS ID2
		FROM SYZHAO.PUBLIC_FRIENDS F
		UNION
		SELECT F.USER2_ID AS ID1, F.USER1_ID AS ID2
		FROM SYZHAO.PUBLIC_FRIENDS F
	)F1,
	(
		SELECT F.USER1_ID AS ID1, F.USER2_ID AS ID2
		FROM SYZHAO.PUBLIC_FRIENDS F
		UNION
		SELECT F.USER2_ID AS ID1, F.USER1_ID AS ID2
		FROM SYZHAO.PUBLIC_FRIENDS F
	)F2,
	(
		SELECT U1.USER_ID AS UID1, U2.USER_ID AS UID2
		FROM SYZHAO.PUBLIC_USERS U1, SYZHAO.PUBLIC_USERS U2
		WHERE U1.USER_ID < U2.USER_ID
		MINUS
		SELECT F.USER1_ID AS UID1, F.USER2_ID AS UID2
		FROM SYZHAO.PUBLIC_FRIENDS F
	)N
	WHERE
	N.UID1 = F1.ID1 AND N.UID2 = F2.ID1 AND F1.ID2 = F2.ID2
	GROUP BY N.UID1, N.UID2
	ORDER BY CommonFri DESC, N.UID1 ASC, N.UID2 ASC
)A
WHERE 
U1.USER_ID = A.UID1 AND U2.USER_ID = A.UID2
AND ROWNUM <= 5;


SELECT DISTINCT 
UID1, UID2, CommonFri
FROM
(
	SELECT N.UID1, N.UID2, COUNT(*) AS CommonFri
	FROM
	(
		SELECT F.USER1_ID AS ID1, F.USER2_ID AS ID2
		FROM SYZHAO.PUBLIC_FRIENDS F
		UNION
		SELECT F.USER2_ID AS ID1, F.USER1_ID AS ID2
		FROM SYZHAO.PUBLIC_FRIENDS F
	)F1,
	(
		SELECT F.USER1_ID AS ID1, F.USER2_ID AS ID2
		FROM SYZHAO.PUBLIC_FRIENDS F
		UNION
		SELECT F.USER2_ID AS ID1, F.USER1_ID AS ID2
		FROM SYZHAO.PUBLIC_FRIENDS F
	)F2,
	(
		SELECT U1.USER_ID AS UID1, U2.USER_ID AS UID2
		FROM SYZHAO.PUBLIC_USERS U1, SYZHAO.PUBLIC_USERS U2
		WHERE U1.USER_ID < U2.USER_ID
		MINUS
		SELECT F.USER1_ID AS UID1, F.USER2_ID AS UID2
		FROM SYZHAO.PUBLIC_FRIENDS F
	)N
	WHERE
	N.UID1 = F1.ID1 AND N.UID2 = F2.ID1 AND F1.ID2 = F2.ID2
	GROUP BY N.UID1, N.UID2
	ORDER BY CommonFri DESC, N.UID1 ASC, N.UID2 ASC
)
WHERE ROWNUM <= 5;
