
SELECT DISTINCT 
UID1, UID2, CommonFri
FROM
(
	SELECT N.UID1, N.UID2, COUNT(*) AS CommonFri
	FROM
	(
		SELECT F.USER1_ID AS ID1, F.USER2_ID AS ID2
		FROM SYZHAO.PUBLIC_FRIENDS F
		UNION
		SELECT F.USER2_ID AS ID1, F.USER1_ID AS ID2
		FROM SYZHAO.PUBLIC_FRIENDS F
	)F1,
	(
		SELECT F.USER1_ID AS ID1, F.USER2_ID AS ID2
		FROM SYZHAO.PUBLIC_FRIENDS F
		UNION
		SELECT F.USER2_ID AS ID1, F.USER1_ID AS ID2
		FROM SYZHAO.PUBLIC_FRIENDS F
	)F2,
	(
		SELECT U1.USER_ID AS UID1, U2.USER_ID AS UID2
		FROM SYZHAO.PUBLIC_USERS U1, SYZHAO.PUBLIC_USERS U2
		WHERE U1.USER_ID < U2.USER_ID
		MINUS
		SELECT F.USER1_ID AS UID1, F.USER2_ID AS UID2
		FROM SYZHAO.PUBLIC_FRIENDS F
	)N
	WHERE
	N.UID1 = F1.ID1 AND N.UID2 = F2.ID1 AND F1.ID2 = F2.ID2
	GROUP BY N.UID1, N.UID2
	ORDER BY CommonFri DESC, N.UID1 ASC, N.UID2 ASC
)
WHERE ROWNUM <= 5;

SELECT U1.FIRST_NAME, U1.LAST_NAME, U2.FIRST_NAME, U2.LAST_NAME
FROM SYZHAO.PUBLIC_USERS U1, SYZHAO.PUBLIC_USERS U2
WHERE U1.USER_ID = 109 AND U2.USER_ID = 122


SELECT A.ID, U.FIRST_NAME, U.LAST_NAME
FROM SYZHAO.PUBLIC_USERS U,
(
	((
		SELECT USER2_ID AS ID
		FROM SYZHAO.PUBLIC_FRIENDS F
		WHERE F.USER1_ID = 109
	)
	UNION
	(	
		SELECT USER1_ID AS ID
		FROM SYZHAO.PUBLIC_FRIENDS F
		WHERE F.USER2_ID = 109
	))
	INTERSECT
	((
		SELECT USER2_ID AS ID
		FROM SYZHAO.PUBLIC_FRIENDS F
		WHERE F.USER1_ID = 122
	)
	UNION
	(	
		SELECT USER1_ID AS ID
		FROM SYZHAO.PUBLIC_FRIENDS F
		WHERE F.USER2_ID = 122
	))
)A
WHERE U.USER_ID = A.ID
ORDER BY A.ID

