(select USER2_ID AS ID from SYZHAO.PUBLIC_FRIENDS where USER1_ID = 386
UNION
select USER1_ID AS ID from SYZHAO.PUBLIC_FRIENDS where USER2_ID = 386)
INTERSECT
(select USER2_ID AS ID from SYZHAO.PUBLIC_FRIENDS where USER1_ID = 1770
UNION
select USER1_ID AS ID from SYZHAO.PUBLIC_FRIENDS where USER2_ID = 1770);


SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME
FROM SYZHAO.PUBLIC_USERS U,
(   
	SELECT F.USER2_ID AS USER_ID
	FROM SYZHAO.PUBLIC_FRIENDS F 
	WHERE
	F.USER1_ID = 1153
	UNION
	SELECT F.USER1_ID AS USER_ID
	FROM SYZHAO.PUBLIC_FRIENDS F 
	WHERE
	F.USER2_ID = 1153
)F
WHERE F.USER_ID = U.USER_ID
ORDER BY U.YEAR_OF_BIRTH DESC, U.MONTH_OF_BIRTH DESC, U.DAY_OF_BIRTH DESC, U.USER_ID DESC;