SELECT U1.USER_ID AS USER1_ID, U1.FIRST_NAME, U1.LAST_NAME, 
U2.USER_ID AS USER2_ID, U2.FIRST_NAME, U2.LAST_NAME
FROM SYZHAO.PUBLIC_USERS U1, SYZHAO.PUBLIC_USERS U2, 
SYZHAO.PUBLIC_USER_HOMETOWN_CITY H1, SYZHAO.PUBLIC_USER_HOMETOWN_CITY H2, 
SYZHAO.PUBLIC_FRIENDS F
WHERE U1.USER_ID = H1.USER_ID AND U2.USER_ID = H2.USER_ID AND 
H1.HOMETOWN_CITY_ID = H2.HOMETOWN_CITY_ID AND 
U1.USER_ID < U2.USER_ID AND U1.USER_ID = F.USER1_ID AND F.USER2_ID = U2.USER_ID AND
ABS(U1.YEAR_OF_BIRTH - U2.YEAR_OF_BIRTH) < 10 AND
U1.LAST_NAME = U2.LAST_NAME
ORDER BY USER1_ID ASC, USER2_ID ASC;